"""incremented password string to 255

Revision ID: 11155a186e55
Revises: 411dc7347dff
Create Date: 2023-11-06 00:59:23.520265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11155a186e55'
down_revision = '411dc7347dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
