"""added user model

Revision ID: 411dc7347dff
Revises: 7a04bdd6bc42
Create Date: 2023-11-06 00:54:33.017710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411dc7347dff'
down_revision = '7a04bdd6bc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
