"""total nullable true

Revision ID: 7a04bdd6bc42
Revises: bc45752d84ef
Create Date: 2023-11-05 21:01:05.734145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a04bdd6bc42'
down_revision = 'bc45752d84ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buy_stock', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buy_stock', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
