"""concat model for db

Revision ID: 824a0fdc6d38
Revises: 11155a186e55
Create Date: 2023-11-06 01:07:51.139145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824a0fdc6d38'
down_revision = '11155a186e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
