"""buyStock

Revision ID: bc45752d84ef
Revises: 7a3d3b53cc0c
Create Date: 2023-11-05 21:00:03.787863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc45752d84ef'
down_revision = '7a3d3b53cc0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buy_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buy_stock')
    # ### end Alembic commands ###
